# Generated by Django 5.0 on 2023-12-11 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contacts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact_name', models.CharField(max_length=100)),
                ('contact_email', models.CharField(max_length=250)),
                ('contact_notes', models.CharField(max_length=250)),
                ('created_time', models.CharField(max_length=25)),
            ],
        ),
    ]
