# Generated by Django 5.0 on 2023-12-11 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pulkit_kamboj_CMS', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contacts',
            name='contact_email',
            field=models.EmailField(max_length=250),
        ),
    ]
